site_name: UA Data Science Institute Trainings
theme:
  name: material

  nav: 
     - 'index.md'
     - 'Unix Shell': 'CommandLineInterface.md'
  # setting features for the navigation tab
  features:
    - navigation.instant
      #- navigation.expand
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: orange 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-0893-4268
    - icon: fontawesome/brands/github
      link: https://github.com/clizarraga-UAD7
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/carloslizarragac/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/carlos.lizarragac/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clizarraga
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.online/@clizarraga
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/clizarraga
    

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
#    - mkdocstrings
#    - git-revision-date
#    - mkdocs-jupyter:
#          include_source: True
#         ignore_h1_titles: True     
# Copyright
copyright: 'Copyright &copy; 2023 Carlos Lizárraga-Celaya'

