site_name: UA Data Science Institute Trainings
site_description: 'Data Science trainings'
site_author: 'Carlos Lizárraga-Celaya'
#site_url: https://trainings-UAD7.github.io/

# Repository
repo_name: trainings-UAD7
repo_url: https://github.com/workshops-UAD7/trainings-UAD7.github.io
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2023 University of Arizona Data Science Institute'

# Page tree
nav: 
  - Home: index.md
  - Command Line Interface: 
    - Command Line Interface: CLI/CommandLineInterface.md
    - Github Codespaces: CLI/Codespaces.md
    - Unix Shell: CLI/UnixShell.md
    - Files & Directories: CLI/Files_Dirs.md
    - Pipes & Filters: CLI/Pipes_Filters.md
    - Loops & Shell Scripts: CLI/Loops_Scripts.md
  - LLM & Prompt Engineering:
    - Prompt Engineneering Basics: LLM/PromptEngBasics.md
    - ChatGPT in Learning Environments: LLM/HE_TeachingEnvironments.md
    - ChatGPT in Higher Education: LLM/ChatGPT_HE.md
 # Configuration
imgwidth: 70px;

theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  #logo: 'assets/uarizona.png'
  #favicon: 'assets/favicon.ico' 
  
  
  # setting features for the navigation tab
  features:
    - navigation.instant
    - navigation.path
    - navigation.expand
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - search.highlight
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep orange 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/space-awesome
      link: https://www.datascience.arizona.edu/person/carlos-lizarraga
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-0893-4268
    - icon: fontawesome/brands/github
      link: https://github.com/clizarraga-UAD7
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/carloslizarragac/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/carlos.lizarragac/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.online/@clizarraga
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/clizarraga
    

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
      #    format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
#    - mkdocstrings
#    - git-revision-date
#    - mkdocs-jupyter:
#          include_source: True
#         ignore_h1_titles: True     
# Copyright
# copyright: 'Copyright &copy; 2023 Carlos Lizárraga-Celaya'

